name: Orchestrate Build of APIs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  catalog:
    uses: ./.github/workflows/docker-build.yaml
    secrets: inherit
    with:
      context: backends
      dockerfile: Catalog.API/Dockerfile
      docker_tag: latest
      service_name: kubefood-catalog-api
  
  order:
    uses: ./.github/workflows/docker-build.yaml
    secrets: inherit
    with:
      context: backends
      dockerfile: Order.API/Dockerfile
      docker_tag: latest
      service_name: kubefood-order-api

  inventory:
    uses: ./.github/workflows/docker-build.yaml
    secrets: inherit
    with:
      context: backends
      dockerfile: Inventory.API/Dockerfile
      docker_tag: latest
      service_name: kubefood-inventory-api